<?php return array (
  'version' => '5.1',
  'enable' => true,
  'debug' => true,
  'domain' => 'localhost',
  'apikey' => 'public',
  'host' => 'localhost',
  'port' => '8000',
  'emot' => 'default',
  'theme' => 'base',
  'opacity' => '80',
  'local' => 'zh-CN',
  'show_realname' => false,
  'enable_room' => false,
  'enable_chatlink' => false,
  'enable_shortcut' => true,
  'enable_menu' => false,
  'enable_login' => false,
  'enable_noti' => true,
  'admin_uids' => '0',
  'visitor' => false,
  'show_unavailable' => true,
  'upload' => false,
);
