<?php $_IMC=array(); $_IMC= array (
  'version' => '4.0',
  'enable' => true,
  'domain' => '',
  'apikey' => '',
  'host' => 'webim20.cn',
  'port' => '8888',
  'theme' => 'base',
  'local' => 'zh-CN',
  'show_realname' => false,
  'disable_room' => false,
  'disable_chatlink' => false,
  'enable_shortcut' => true,
  'emot' => 'default',
  'opacity' => '80',
  'disable_menu' => false,
  'enable_login' => false,
  'host_from_domain' => false,
  'admin_uid' => '0',
  'admin_groupname' => 'admin',
);
